### PR TITLE
Add Quest String based ID support

### LINKED ISSUE #52: Allow string based player ID to allow for Quest version of pavlovserver
Pavlovserver has been released for Quest. Pavlov-bot isn't fully compatible with this version due to differences in ID format for players. Currently SteamID uses a integer while Quest uses a hex ID (e.g. E47FB3C7BDC536B8). Currently pavlov bot checks if a playerID is an int and otherwise assumes it is an alias. 

This enhancement would change player ID to allow either int or string and enhanced testing of input to determine if playername input is either a QuestID or an alias to be looked up.

### PR DESCRIPTION
**Pull request by makupi**
- If "player" argument passed is an `integer` it is used directly as an argument
- `NEW`: If argument is a `string` with a length >= **16** and hexadecimal (e.g. `0022a0356594df59ebaf8ce9c10f145`) it is used directly as an argument.
- For all other cases, it is checked whether the `string` argument passed is defined as an alias.

This should work for both Quest IDs mentioned in #52 

Closes #52

### CODE REVIEW

**Comment by Archaeo2386** [comment]
Tested the quest-string-id branch and it works flawlessly with the EOS ids used for the quest version.

**Comment by makupi** [comment]
> Tested the quest-string-id branch and it works flawlessly with the EOS ids used for the quest version.

Awesome! Thank you for testing. I'll wait for @invicta-nz's feedback and then merge it tomorrow!

**Comment by invicta-nz** [comment]
Have done a fair amount of testing and so far have only one "issue". When you load up the aliases.json file the longer EOS ID requires quoting or the bot errors out on startup. So file has two formats now:
```
  "players": {
    "player1": "0029591b8c44a08af17b4b3bc705aa0",
    "player2": 76561197964679479,
..SNIP...
  "teams": {
    "rawdoggers": ["0029591b8c44a08af17b4b3bc705aa0", 76561198397498572, 76561198335856838, 76561197964679479, 76561197963503245, 76561198040369284, 76561198134112143],
```

This seems to work fine in both cases. As long as this doesn't indicate an underlying problem with parsing, I guess it is just something that needs to be documented.

**Comment by makupi** [comment]
The string in the .json is an "issue" of the file format, since the EOS IDs *are* strings after all. Parsing wise this is fine, it should even work if you write all IDs as strings I'm pretty sure.

**Comment by invicta-nz** [comment]
Ok, let me test that converting everything into strings works and then update the aliases.json.example files to only show this new format to reduce confusion for new admins.

**Review by invicta-nz — APPROVED** [review]
Tested change of all userIDs into strings. Looks good

**Pull request merged**
