### PR TITLE
Add configurable default server to allow omitting server name

### PR DESCRIPTION
**Pull request by psimyn**
Disclaimer: I have no idea what I'm doing

Add config option for `server_name` then pass as default value for server param to all commands.

Should this actually affect all commands? Maybe for some things (like admin commands, at least for `blacklist`) it's better to require specifying a server. I wasn't sure how to update the docs for each separately so consistency was easier.

Also not sure if using `None` then assignment is preferable to using config directly. Since we could potentially then mutate the config option

Fixes https://github.com/makupi/pavlov-bot/issues/56

### CODE REVIEW

**Comment by frostyboskitzo** [comment]
As a comment, Psimyn and I tested this on our homey little discord, and it checks out, seemingly with good handling.
* `;switchmap badmapaliasname DM` still errors correctly with unrecognised alias.
* `;switchmap goodaliasname` still errors correctly with "too few arguments" because game mode is missing.
* `;switchmap goodaliasname SND` uses the first server from servers.json. 

There _is_ a weird bug if that noone has joined the server, the Pavlov server doesn't report the new info under ;serverinfo, but that exists in the current master branch, so I'm confident it's not introduced by this PR.

That bug might be a pavlov-server issue; UE4 might have some triggers that rely on connected clients before it does certain things.

**Review by frostyboskitzo — COMMENTED** [review]
@psimyn Given this PR potentially changes the syntax of config.json, I would recommend either editing `config.json.example` (or whatever it's called in `./examples` to reflect the server default, or explicitly having the jsonified format in full in the README.md.

**Comment by invicta-nz** [comment]
I have a league match up tonight, but will load this branch in my test environment tomorrow and have a play. 
What is expected behaviour if `default_server` isn't set in `config.json`? Is an updated `config.json` required?

**Comment by psimyn** [comment]
Updated example config, I didn't update readme though, since the content is the same we could probably reduce that.

@invicta-nz if it's not set it uses "default". [config.py](https://github.com/psimyn/pavlov-bot/blob/default-server/bot/utils/config.py#L18) has default values for everything, so the only value you actually need in config.json is "token"

**Review by makupi — COMMENTED** [review]
Looks good to me. I'll wait for the test results from @invicta-nz before approval, thanks for the contribution though!

**Review by invicta-nz — CHANGES_REQUESTED** [review]
The ``;matchsetup`` command was missed. Can we make this change as well for consistency please? Other than than that have tested the code pretty thoroughly with no issues found.

**Comment by psimyn** [comment]
good pickup @invicta-nz - I'd done find/replace and that one didn't have `)` on the same line 🤦 

Updated and added

**Review by invicta-nz — APPROVED** [review]
Looks good.. merging into master

**Pull request merged**
